### ISSUE TITLE
Mark5B files with no stop time

### ISSUE THREAD

**Issue by 00rebe** [mhvk/baseband#274]
Hi,

I noticed that in the EK036c Crab observation, certain data files do not seem to have a stop time. The file format for these are all Mark5B.

Here is a list of the files in folder `/mnt/raid-project/gmrt/rlin/ek036c/` that do not have a stop time:

`bd/ek036c_bd_no0028.m5a`

`ur/ek036c_ur_no0020.m5a`

`zc/ek036c_zc_no0005.m5a`
`zc/ek036c_zc_no0009.m5a`
`zc/ek036c_zc_no0024.m5a`

Here is some iPython output using a file, `"ek036c_bd_no0028.m5a"` to illustrate that:

```
In[1]: from astropy.time import Time

In[2]: import astropy.units as u

In[3]: from baseband import mark5b

In[4]: data_folder = '/mnt/raid-project/gmrt/rlin/ek036c/bd/'

In[5]: filename = 'ek036c_bd_no0028.m5a' 

In[6]: in_file = data_folder + filename

In[7]: nchan=16

In[8]: sample_rate = 32 * u.MHz

In[9]: ref_time = Time(57809, format='mjd')

In[11]: fh = mark5b.open(in_file, mode='rs', nchan=nchan, sample_rate=sample_rate,
                         ref_time=ref_time)

In[13]: fh.stop_time
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/opt/python/3.6.4/lib/python3.6/site-packages/astropy/utils/decorators.py in __get__(self, obj, owner)
    705         try:
--> 706             return obj.__dict__[self._key]
    707         except KeyError:

KeyError: 'stop_time'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
/opt/python/3.6.4/lib/python3.6/site-packages/astropy/utils/decorators.py in __get__(self, obj, owner)
    705         try:
--> 706             return obj.__dict__[self._key]
    707         except KeyError:

KeyError: '_last_header'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
/opt/python/3.6.4/lib/python3.6/site-packages/astropy/utils/decorators.py in __get__(self, obj, owner)
    705         try:
--> 706             return obj.__dict__[self._key]
    707         except KeyError:

KeyError: '_last_header'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-2-9a3d4a04ad59> in <module>()
     23         # fh.info
     24         print(fh.start_time)
---> 25         print(f'{file_num}: {fh.stop_time.isot}')

/opt/python/3.6.4/lib/python3.6/site-packages/astropy/utils/decorators.py in __get__(self, obj, owner)
    706             return obj.__dict__[self._key]
    707         except KeyError:
--> 708             val = self.fget(obj)
    709             obj.__dict__[self._key] = val
    710             return val

/mnt/raid-cita/rlin/packages/baseband/baseband/vlbi_base/base.py in stop_time(self)
    438         the time of the sample pointer's current offset.
    439         """
--> 440         return (self._get_time(self._last_header) +
    441                 (self.samples_per_frame / self.sample_rate).to(u.s))
    442

/opt/python/3.6.4/lib/python3.6/site-packages/astropy/utils/decorators.py in __get__(self, obj, owner)
    706             return obj.__dict__[self._key]
    707         except KeyError:
--> 708             val = self.fget(obj)
    709             obj.__dict__[self._key] = val
    710             return val

/mnt/raid-cita/rlin/packages/baseband/baseband/mark5b/base.py in _last_header(self)
    308     def _last_header(self):
    309         """Last header of the file."""
--> 310         last_header = super(Mark5BStreamReader, self)._last_header
    311         # Infer kday, assuming the end of the file is no more than
    312         # 500 days away from the start.

/opt/python/3.6.4/lib/python3.6/site-packages/astropy/utils/decorators.py in __get__(self, obj, owner)
    706             return obj.__dict__[self._key]
    707         except KeyError:
--> 708             val = self.fget(obj)
    709             obj.__dict__[self._key] = val
    710             return val

/mnt/raid-cita/rlin/packages/baseband/baseband/vlbi_base/base.py in _last_header(self)
    425         with self.fh_raw.temporary_offset() as fh_raw:
    426             fh_raw.seek(-self.header0.frame_nbytes, 2)
--> 427             last_header = fh_raw.find_header(forward=False)
    428         if last_header is None:
    429             raise ValueError("corrupt VLBI frame? No frame in last {0} bytes."

/mnt/raid-cita/rlin/packages/baseband/baseband/mark5b/base.py in find_header(self, forward, maximum)
    159             try:
    160                 self.seek(frame)
--> 161                 header1 = self.read_header()
    162             except AssertionError:
    163                 continue

/mnt/raid-cita/rlin/packages/baseband/baseband/mark5b/base.py in read_header(self)
     62         """
     63         return Mark5BHeader.fromfile(self, kday=self.kday,
---> 64                                      ref_time=self.ref_time)
     65
     66     def read_frame(self, verify=True):

/mnt/raid-cita/rlin/packages/baseband/baseband/vlbi_base/header.py in fromfile(cls, fh, *args, **kwargs)
    351         if len(s) != cls._struct.size:
    352             raise EOFError
--> 353         return cls(cls._struct.unpack(s), *args, **kwargs)
    354
    355     def tofile(self, fh):

/mnt/raid-cita/rlin/packages/baseband/baseband/mark5b/header.py in __init__(self, words, kday, ref_time, verify, **kwargs)
     86             self.kday = kday
     87         elif ref_time is not None:
---> 88             self.infer_kday(ref_time)
     89         if verify:
     90             self.verify()

/mnt/raid-cita/rlin/packages/baseband/baseband/mark5b/header.py in infer_kday(self, ref_time)
    179             Reference time within 500 days of the observation time.
    180         """
--> 181         self.kday = np.round(ref_time.mjd - self.jday, decimals=-3).astype(int)
    182
    183     @property

/mnt/raid-cita/rlin/packages/baseband/baseband/mark5b/header.py in jday(self)
    206     def jday(self):
    207         """Last three digits of MJD (decoded from 'bcd_jday')."""
--> 208         return bcd_decode(self['bcd_jday'])
    209
    210     @jday.setter

/mnt/raid-cita/rlin/packages/baseband/baseband/vlbi_base/utils.py in bcd_decode(value)
     13     try:
     14         # Far faster than my routine for scalars
---> 15         return int('{:x}'.format(index(value)))
     16     except TypeError as exc:  # Might still be an array
     17         try:

ValueError: invalid literal for int() with base 10: '9ca'
```

**Comment by mhvk** [comment]
Here, there is a similar problem as for the VDIF files, that the files are truncated in the middle of a frame, but the problem was a bit more subtle, in that in trying to find the correct start of a frame, the code attempted to read bytes as headers that were simply wrong. Anyway, fix in #275 - though at least the first example you gave also seems to have a missing frame...

**Comment by mhvk** [comment]
I think the first cause is fixed now, but some files still may have problems because of missing frames...

**Comment by 00rebe** [comment]
@mhvk I still can't seem to read the stop time for any of these files. Must be that all of them have missing frames...

**Comment by mhvk** [comment]
Missing frames should not cause a problem with the stop time - I'll have a look...

**Comment by mhvk** [comment]
@00rebe - I tried the first two files, and for both I can now see `stop_time`; in the second file, the following also worked:
```
fh.seek(fh.start_time + 0.9*(fh.stop_time-fh.start_time))
# 8528024250
fh.read(10)
```
Did you perhaps forget to update to current master?
